version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 1000
    reviewers:
      - jwhitlock
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - jwhitlock
  - package-ecosystem: docker
    directory: /docker/node/
    schedule:
      interval: monthly
    open-pull-requests-limit: 1000
    reviewers:
      - jwhitlock
  - package-ecosystem: npm
    directory: /docker/node/
    schedule:
      interval: monthly
    reviewers:
      - jwhitlock
