version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/ichnaea_app
    env_file:
      - docker/config/local_dev.env
      - my.env
    volumes:
      - .:/app

  web:
    image: local/ichnaea_app
    env_file:
      - docker/config/local_dev.env
      - my.env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: ["web"]
    ports:
      - "8000:8000"

  scheduler:
    image: local/ichnaea_app
    env_file:
      - docker/config/local_dev.env
      - my.env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: ["scheduler"]

  worker:
    image: local/ichnaea_app
    env_file:
      - docker/config/local_dev.env
      - my.env
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: ["worker"]

  # Used for building CSS and JS assets
  node:
    build:
      context: ./docker/node/
      dockerfile: Dockerfile
    volumes:
      - .:/app

  db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    expose:
      - "3306"
    ports:
      - "3306"

  redis:
    image: redis:3.2
    expose:
      - "6379"
    ports:
      - "6379:6379"
