version: 2.1
jobs:
  build:
    docker:
      - image: mozilla/cidockerbases:docker-latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /

    steps:
        - run:
            name: Host info
            command: uname -v

        - run:
            name: Install essential packages
            command: |
                apt-get update

        - checkout:
            path: /ichnaea

        - run:
            name: Create version.json
            working_directory: /ichnaea
            command: |
                # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
                printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
                "$CIRCLE_SHA1" \
                "$CIRCLE_TAG" \
                "$CIRCLE_PROJECT_USERNAME" \
                "$CIRCLE_PROJECT_REPONAME" \
                "$CIRCLE_BUILD_URL" > /ichnaea/version.json

        - store_artifacts:
            path: /ichnaea/version.json

        - setup_remote_docker:
            version: 19.03.13

        - run:
            name: Get Info
            command: |
               docker info
               which docker-compose
               docker-compose --version

        - run:
            name: Login to Dockerhub
            command: |
                if [ "${DOCKER_USER}" == "" ] || [ "${DOCKER_PASS}" == "" ]; then
                  echo "Skipping Login to Dockerhub, credentials not available."
                else
                  echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
                fi

        - run:
            name: Build Docker images
            working_directory: /ichnaea
            command: |
                make build

        - run:
            name: Verify requirements
            working_directory: /ichnaea
            command: |
                docker run --user root local/ichnaea_app shell ./docker/regenerate_requirements.sh --verify

        - run:
            name: Run linting
            working_directory: /ichnaea
            command: |
                docker run local/ichnaea_app shell ./docker/run_lint.sh

        - run:
            name: Run tests
            working_directory: /ichnaea
            command: |
                make test

        - run:
            name: Push to Dockerhub
            working_directory: /ichnaea
            command: |
              function retry {
                set +e
                local n=0
                local max=3
                while true; do
                "$@" && break || {
                  if [[ $n -lt $max ]]; then
                    ((n++))
                    echo "Command failed. Attempt $n/$max:"
                  else
                    echo "Failed after $n attempts."
                    exit 1
                  fi
                }
                done
                set -e
              }

              export DOCKER_TAG="${CIRCLE_SHA1}"
              if [ -n "${CIRCLE_TAG}" ]; then
                export DOCKER_TAG="${CIRCLE_TAG}"
              fi
              # push on main or git tag
              if [ "${CIRCLE_BRANCH}" == "main" ] || [ -n "${CIRCLE_TAG}" ]; then
                docker tag "local/ichnaea_app" "mozilla/location:${DOCKER_TAG}"
                retry docker push "mozilla/location:${DOCKER_TAG}"

                # push `latest` on main only
                if [ "${CIRCLE_BRANCH}" == "main" ]; then
                  docker tag "local/ichnaea_app" "mozilla/location:latest"
                  retry docker push "mozilla/location:latest"
                fi
              else
                echo "Skipping Push to Dockerhub, not main or tag."
              fi

workflows:
  version: 2
  #
  # workflow jobs are _not_ run in tag builds by default, so we have to enable that.
  # see: https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
  build-test-push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
